UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=674;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=675;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=677;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=737;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=773;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6 WHERE `creature_id`=921;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=1094;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=1095;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=1096;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=1097;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=1411;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=1783;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=1784;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=1785;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=1787;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=1788;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=1789;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=1791;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=1793;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=1794;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=1795;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=1796;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=1802;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=1804;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=1805;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 15 WHERE `creature_id`=1847;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 7, `RewOnKillRepValue1` = 15 WHERE `creature_id`=1852;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2482;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2487;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2488;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2490;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2491;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2493;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2494;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2495;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=2496;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2498;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2499;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2500;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2501;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2502;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2542;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2594;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2622;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=2625;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2627;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=2636;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2663;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2664;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2670;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2685;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2699;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=2769;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=2778;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2832;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2834;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2836;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2837;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2838;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2839;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2840;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2842;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2843;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2844;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2845;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2846;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2847;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2848;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=2849;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=3945;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=4260;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=4472;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=4474;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=4475;
UPDATE `creature_onkill_reputation` SET `MaxStanding2` = 5 WHERE `creature_id`=4624;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=4631;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4638;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4639;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4640;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4641;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4642;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4643;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4644;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4645;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4646;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4647;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4648;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4649;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4651;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4652;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4653;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `creature_id`=4661;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 100, `MaxStanding2` = 4, `RewOnKillRepValue2` = -500 WHERE `creature_id`=4662;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=4723;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 100, `MaxStanding2` = 4, `RewOnKillRepValue2` = -500 WHERE `creature_id`=5601;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 10 WHERE `creature_id`=5615;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 10 WHERE `creature_id`=5616;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 10 WHERE `creature_id`=5617;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 10 WHERE `creature_id`=5618;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 10 WHERE `creature_id`=5623;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 100, `MaxStanding2` = 4, `RewOnKillRepValue2` = -500 WHERE `creature_id`=6068;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=7153;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=7154;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=7155;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=7156;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=7157;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=7158;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=7406;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=7438;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=7439;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=7440;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=7441;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=7442;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=7794;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 25 WHERE `creature_id`=7847;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=7853;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8123;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = -125 WHERE `creature_id`=8320;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8523;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8524;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8525;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8526;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8527;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8528;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8529;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8530;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=8531;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8532;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8534;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8535;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8538;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8539;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8540;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8541;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8542;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=8543;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8544;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=8545;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=8546;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=8547;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=8548;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=8550;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=8551;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=8553;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8555;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8556;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=8557;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=8558;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 15 WHERE `creature_id`=9462;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 15 WHERE `creature_id`=9464;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10199;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10381;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10382;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10384;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10385;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10390;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10391;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10398;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10399;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10400;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10405;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10406;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10407;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10408;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10409;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10412;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10413;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10414;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10416;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10417;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10432;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10433;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10435;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10436;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10437;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10438;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 50 WHERE `creature_id`=10440;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10463;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10464;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10469;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10470;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10471;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10476;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10477;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10478;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10480;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10481;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10482;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10485;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10486;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10487;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10488;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10489;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10491;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10495;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10498;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10499;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10500;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10502;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10503;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10504;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10505;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10507;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 50 WHERE `creature_id`=10508;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10558;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=10580;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=10698;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10738;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=10801;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10809;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=10816;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 15 WHERE `creature_id`=10821;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 15 WHERE `creature_id`=10825;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 15 WHERE `creature_id`=10826;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=10827;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=10901;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=10916;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=11082;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=11257;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=11261;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11338;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11339;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11340;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11350;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11351;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11352;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11353;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11356;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11359;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11361;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11365;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11370;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11371;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11372;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11373;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11374;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=11551;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=11582;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=11622;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 1 WHERE `creature_id`=11803;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 1 WHERE `creature_id`=11804;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11830;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=11831;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=11873;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 1 WHERE `creature_id`=11880;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 1 WHERE `creature_id`=11881;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 1 WHERE `creature_id`=11882;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 1 WHERE `creature_id`=11883;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepFaction1` = 169 WHERE `creature_id`=12136;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=12262;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `creature_id`=12263;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=14342;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=14479;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=14532;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=14750;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=14821;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=14825;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=14861;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=14880;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=14882;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=14883;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=15043;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5 WHERE `creature_id`=15111;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15168;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 1 WHERE `creature_id`=15200;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 1 WHERE `creature_id`=15201;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 1 WHERE `creature_id`=15202;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 50 WHERE `creature_id`=15204;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 50 WHERE `creature_id`=15205;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=15206;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=15207;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=15208;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=15209;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=15211;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=15212;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 1 WHERE `creature_id`=15213;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=15220;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 50 WHERE `creature_id`=15305;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=15307;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 5 WHERE `creature_id`=15308;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15318;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15319;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15320;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15323;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15324;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15325;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15327;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15333;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15335;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15336;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15338;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = 300 WHERE `creature_id`=15339;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = 150 WHERE `creature_id`=15340;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 34 WHERE `creature_id`=15341;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = 150 WHERE `creature_id`=15348;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15355;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = 150 WHERE `creature_id`=15369;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = 150 WHERE `creature_id`=15370;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15461;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15462;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15537;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `creature_id`=15538;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `creature_id`=15541;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 1 WHERE `creature_id`=15542;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepFaction1` = 609, `RewOnKillRepValue1` = 500 WHERE `creature_id`=15547;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 25 WHERE `creature_id`=15623;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue2` = 500 WHERE `creature_id`=15727;
UPDATE `creature_onkill_reputation` SET `RewOnKillRepValue1` = 15 WHERE `creature_id`=16184;
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 20, `MaxStanding2` = 4, `RewOnKillRepValue2` = -100 WHERE `creature_id`=5602;

-- Prevents reputation gained from Sethekk Halls to go beyond Honored
UPDATE `creature_onkill_reputation` SET `MaxStanding1`=5 WHERE `creature_id` IN (18318,18319,18320,18321,18322,18323,18325,18326,18327,18328,18472,18473,19428,19429,21891,21904,21931);
