UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=737;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=773;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=1411;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=1783;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=1784;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=1785;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=1787;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=1788;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=1789;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=1791;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=1793;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=1794;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=1795;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=1796;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=1802;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=1804;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=1805;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 15 WHERE `entry`=1847;
UPDATE `creature_template` SET `MaxStanding1` = 7, `RewOnKillRepValue1` = 15 WHERE `entry`=1852;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2482;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2487;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2488;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2490;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2491;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2493;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2494;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2495;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=2496;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2498;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2499;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2500;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2501;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2502;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2542;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2594;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2622;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=2625;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2627;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=2636;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2663;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2664;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2670;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2685;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2699;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=2769;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=2778;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2832;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2834;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2836;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2837;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2838;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2839;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2840;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2842;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2843;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2844;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2845;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2846;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2847;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2848;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=2849;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=3945;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=4472;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=4474;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=4475;
UPDATE `creature_template` SET `MaxStanding2` = 5 WHERE `entry`=4624;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=4631;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4638;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4639;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4640;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4641;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4642;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4643;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4644;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4645;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4646;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4647;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4648;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4649;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4651;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4652;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4653;
UPDATE `creature_template` SET `MaxStanding1` = 4, `MaxStanding2` = 4 WHERE `entry`=4661;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 100, `MaxStanding2` = 4, `RewOnKillRepValue2` = -500 WHERE `entry`=4662;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=4723;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 100, `MaxStanding2` = 4, `RewOnKillRepValue2` = -500 WHERE `entry`=5601;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 10 WHERE `entry`=5615;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 10 WHERE `entry`=5616;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 10 WHERE `entry`=5617;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 10 WHERE `entry`=5618;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 10 WHERE `entry`=5623;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 100, `MaxStanding2` = 4, `RewOnKillRepValue2` = -500 WHERE `entry`=6068;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=7153;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=7154;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=7155;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=7156;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=7157;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=7158;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=7406;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=7438;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=7439;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=7440;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=7441;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 6 WHERE `entry`=7442;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=7794;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 25 WHERE `entry`=7847;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=7853;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8123;
UPDATE `creature_template` SET `RewOnKillRepValue2` = -125 WHERE `entry`=8320;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8523;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8524;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8525;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8526;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8527;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8528;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8529;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8530;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=8531;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8532;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8534;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8535;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8538;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8539;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8540;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8541;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8542;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=8543;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8544;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=8545;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=8546;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=8547;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=8548;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=8550;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=8551;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=8553;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8555;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8556;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=8557;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=8558;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 15 WHERE `entry`=9462;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 15 WHERE `entry`=9464;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10199;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10381;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10382;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10384;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10385;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10390;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10391;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10398;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10399;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10400;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10405;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10406;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10407;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10408;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10409;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10412;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10413;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10414;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10416;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10417;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10432;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10433;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10435;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10436;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10437;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10438;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 50 WHERE `entry`=10440;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10463;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10464;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10469;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10470;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10471;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10476;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10477;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10478;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10480;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10481;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10482;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10485;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10486;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10487;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10488;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10489;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10491;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10495;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10498;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10499;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=10500;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10502;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10503;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10504;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10505;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10507;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 50 WHERE `entry`=10508;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10558;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=10580;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=10698;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10738;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=10801;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10809;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=10816;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 15 WHERE `entry`=10821;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 15 WHERE `entry`=10825;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 15 WHERE `entry`=10826;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=10827;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=10901;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=10916;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=11082;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=11257;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=11261;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11338;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11339;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11340;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11350;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11351;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11352;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11353;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11356;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11359;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11361;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11365;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11370;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11371;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11372;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11373;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11374;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=11551;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=11582;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=11622;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 1 WHERE `entry`=11803;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 1 WHERE `entry`=11804;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11830;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=11831;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=11873;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 1 WHERE `entry`=11880;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 1 WHERE `entry`=11881;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 1 WHERE `entry`=11882;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 1 WHERE `entry`=11883;
UPDATE `creature_template` SET `RewOnKillRepFaction1` = 169 WHERE `entry`=12136;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=12262;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 5 WHERE `entry`=12263;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=14342;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=14479;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=14532;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=14750;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=14821;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=14825;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=14861;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=14880;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=14882;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=14883;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=15043;
UPDATE `creature_template` SET `MaxStanding1` = 5 WHERE `entry`=15111;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15168;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 1 WHERE `entry`=15200;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 1 WHERE `entry`=15201;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 1 WHERE `entry`=15202;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 50 WHERE `entry`=15204;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 50 WHERE `entry`=15205;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=15206;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=15207;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=15208;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=15209;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=15211;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=15212;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 1 WHERE `entry`=15213;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=15220;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 50 WHERE `entry`=15305;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=15307;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 5 WHERE `entry`=15308;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15318;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15319;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15320;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15323;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15324;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15325;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15327;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15333;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15335;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15336;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15338;
UPDATE `creature_template` SET `RewOnKillRepValue2` = 300 WHERE `entry`=15339;
UPDATE `creature_template` SET `RewOnKillRepValue2` = 150 WHERE `entry`=15340;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 34, `RewOnKillRepValue2` = 100 WHERE `entry`=15341;
UPDATE `creature_template` SET `RewOnKillRepValue2` = 150 WHERE `entry`=15348;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15355;
UPDATE `creature_template` SET `RewOnKillRepValue2` = 150 WHERE `entry`=15369;
UPDATE `creature_template` SET `RewOnKillRepValue2` = 150 WHERE `entry`=15370;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15461;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15462;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15537;
UPDATE `creature_template` SET `MaxStanding1` = 6, `RewOnKillRepValue1` = 3 WHERE `entry`=15538;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 5 WHERE `entry`=15541;
UPDATE `creature_template` SET `MaxStanding1` = 5, `RewOnKillRepValue1` = 1 WHERE `entry`=15542;
UPDATE `creature_template` SET `RewOnKillRepFaction1` = 609, `RewOnKillRepValue1` = 500 WHERE `entry`=15547;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 25 WHERE `entry`=15623;
UPDATE `creature_template` SET `RewOnKillRepValue2` = 500 WHERE `entry`=15727;
UPDATE `creature_template` SET `RewOnKillRepValue1` = 15 WHERE `entry`=16184;
UPDATE `creature_template` SET `MaxStanding1` = 4, `RewOnKillRepValue1` = 20, `MaxStanding2` = 4, `RewOnKillRepValue2` = -100 WHERE `entry`=5602;
